names = ['Mike', 'Jack', 'Alice', "Job", "Tom"]

print('a' == 'a')
print('a' == 'A')
print('A'.lower() == 'a')
print('A'.lower() == 'A')
print(5 == 2)
print(2 != 2)
print(3 >= 1)
print(3 < 1)
print('a' == 'a' and 'b' == 'b')
print('a' == 'a' and 'b' == 'A')
print('a' == 'a' or 'b' == 'A')
print('C' == 'a' or 'b' == 'A')
print('Bob' in names)
print('Amy' in names)
print('Tim' not in names)
print('Tom' not in names)